### ISSUE TITLE
Site box doesnt allow scrolling

### ISSUE THREAD

**Issue by Optimumfireworks** [firebywire/User-Issues#12]
the firing site entry box in the cue allocation table doesn't allow scrolling of the sites as it originally did and this adds a significant time as now a click to create the drop down list is needed and click to select, scrolling is a far faster additional option as per version 1 for this as it has to be done very regularly.

**Comment by mlepyro** [comment]
How do you mean?  Scrolling works for me.  But you have to click first to select the box (which is normal)?
