### ISSUE TITLE
Editing firework doesn't then correct the name of it

### ISSUE THREAD

**Issue by Optimumfireworks** [firebywire/User-Issues#13]
If "red strobe bombette" is altered to "Red Strobing Bombette" for example, it saves the edited field in the database fine and when you go back into the edit popup window the changes are still there but the name of the firework will not change to reflect the new entry.

this is the same for all the entry fields I noticed such as manufacturer and product code too

**Comment by mlepyro** [comment]
New Database structure proposed will fix this.

**Comment by mlepyro** [comment]
Please test this Phill

**Comment by Optimumfireworks** [comment]
No change at all in V2.0.3.

If you edit any of the information of an existing firework that determines its name (ie diameter, effect and manufacturer) the name does not change at the bottom as it should. If however you delete the name, when you click off it, it recreates the name properly and then continues to edit it while you're in the window. It is just the automatic recreation of the name that appears to be broken as once you've deleted the name, it then corrects it in live mode as it should.

**Comment by mlepyro** [comment]
![image](https://user-images.githubusercontent.com/38982644/54368605-5b149a80-466c-11e9-8a98-072419f3c08c.png)

**Comment by Optimumfireworks** [comment]
Personally I think this is the worst way of doing it, especially if after clicking the button you then would have to click it again if you changed any of the data entry that created the name.
Currently V2.0.3 allows you to delete the name and when unselected the name does what it originally did of generating an autoname and continue to update it as a when the parametres used to create it are changed. That's actually better than having to click a button each time to regenerate it. Even a tick box that stays selected with your choice would be better than having to keep clicking a button. But this then would be no use as a generic choice because other fireworks you wouldn't want it to do so, so it would have to be saved in the DB as an on/off selection for that firework, in which case having it autoselected as on would allow the normal functionality to continue, but the new feature to be allowed. 

Ideally IF the name is already derived from the data entry points above, it should automatically update to stay in line with them (as V1 did). If we now have the extra ability to choose the name of the firework rather than have it automatically assigned this should be an extra option and if the name has been optionally changed it should stay with that manually inputted name unless it is again manually updated.

**Comment by mlepyro** [comment]
New button added
