### ISSUE TITLE
Delete key

### ISSUE THREAD

**Issue by Optimumfireworks** [firebywire/User-Issues#16]
Undo and redo now work on Ctrl shortcuts but delete still doesnt work for deleting a cue?

**Comment by mlepyro** [comment]
Delete button clears the item focused, like it would in excel.

**Comment by mlepyro** [comment]
Maybe if we use the DEL key it asks to delete that row?

If the row is a single firework in a single cue, asks to delete cue.
If the row is one of say 7 fireworks in a cue, asks if want to delete the firework row only, or the cue (all 78 fireworks)

**Comment by Optimumfireworks** [comment]
Id say the easiest thing is for it to bring up the selection window associated with the choice you may mean (ie if youd right clicked on the cue grid) but if you click a cue line on the wav file can it not apreciate you clearly mean to delete it (same as clicking delete cue on the top icon bar)

**Comment by mlepyro** [comment]
F4 is the key.
