### ISSUE TITLE
"Add type" bug

### ISSUE THREAD

**Issue by Optimumfireworks** [firebywire/User-Issues#18]
if you use the add type button and dont select the "save permenently" check box it simply clears all the data you entered, no custom firework is entered into the cue table and nothing is in the searchable database curently open or permenently saved. its just lost forever it seems.

**Comment by mlepyro** [comment]
So this only appears in autocomplete, the "temporary firework" doesn't get added to the firework database on bottom left of screen.

Propose add to this database and has a light grey background to indicate it's a firework only for this show.

**Comment by Optimumfireworks** [comment]
That wasn't the problem that I experienced. The custom firework data that you had entered was simply never entered into the cue that you were writing it out for. ie it was a bug that asked you to enter details but then did not do with those details the thing that you had been asked to put them in for. 

Is your proposal that custom fireworks appear in the bottom left search function as this display would now show global database fireworks and local custom fireworks within it? I don't think thats a bad idea.
