### ISSUE TITLE
Song segments bar

### ISSUE THREAD

**Issue by Optimumfireworks** [firebywire/User-Issues#19]
The bar containing the song data above the wav file seems to now occupy a large space, more than before and certainly more than needed so is wastefull of space

**Comment by IllusionFireworks** [comment]
Yes noticed this too, be useful to be able to resize the pane.

**Comment by Optimumfireworks** [comment]
In version 2.0.1 this is still the same and has not been rectified? It uses up valuable space and should not be the way it is. Either adjustability or correct scaling needs to be reinstated.
