### ISSUE TITLE
Local copy of firework data looses entries

### ISSUE THREAD

**Issue by Optimumfireworks** [firebywire/User-Issues#21]
It appers that when you have a show open (only when you actually load it not already have it open) it opens the edit firework window based on the local "show copy" of the fireworks data, not the database version of it any more, the local copy seems to loose data entry fields such as NEQ

so if you create a new show

put in three cues

add three fireworks (test1 test2 test3) (one to each cue and each with 1kg neq) the total neq is 3kg

save the show

close designer or just reload the show

the neq is still shown as 3kg at the base and when searching the test fireworks their neq still shows 1kg each but when you click edit it shows an neq of 0kg 

..............................................................

as a help in fault finding if you edit the name of the firework in the db (not inside designer but by text entry) it disassociates the firework in the show from the one in the database but this then results in designer seeing it as a custom firework but with an NEQ of 0kg so the shows neq drops

**Comment by mlepyro** [comment]
Linked to Database change proposed.

**Comment by mlepyro** [comment]
Phil please test this on latest build
