### ISSUE TITLE
FireworkTypes.xml

### ISSUE THREAD

**Issue by Komodo-Fireworks** [firebywire/User-Issues#22]
Custom Database - If any field entries are left blank in your database it will not allow you to input the firework into a show or edit within the editor within designer software -

For example if the product code is left blank - you cant add the firework to a cue.

**Comment by mlepyro** [comment]
What Rob means here is if you add a firework into fireworktypes.xml but do not fill out all fields (e.g. forget product code), it won't allow you to use that firework in the show designer.

**Comment by Optimumfireworks** [comment]
MY V2 however will allow me to do this without any issue?
