### ISSUE TITLE
Drag & drop of show data

### ISSUE THREAD

**Issue by Komodo-Fireworks** [firebywire/User-Issues#23]
You can no longer copy and paste the  designer cue grid output in its entirety to Excel - When you highlight all of the fields and do a Ctrl +C  it only copies the ignite time rather than the whole cue details line - When producing the display fusing paperwork, we find it far easier to export the whole cue grid & then manipulate the  output from designer in excel to produce individual product specific prep sheets and print out individual sheets for shells, single shots and candles etc. We find this eliminates lots of errors at the fusing shed.

Can there not be a function to export the cue grid to excel in the designer s/w as displayed format when you print the show plan as well as the split by firing site option we currently have? 

the ability to cut and paste the entire cue grid was a really useful feature to us in the previous S/W version and would like it back please  :-)

**Comment by Komodo-Fireworks** [comment]
Point of note  - there is another bug here as when you try and print the show plan for specific sites by unchecking any of the boxes it does not work and bugs out with an error - you can only print the output with all sites selected.

**Comment by mlepyro** [comment]
Thanks Rob, funnily enough a lot of people wanted this change.  Will look at making it optionable.

**Comment by Optimumfireworks** [comment]
What was asked for mat as I know V1 copied all the data in the row when trying to copy just the name (ie a bug) but surely now this is cured if you select the whole cue grid it should copy all the cue grid as thats whats been selected?

**Comment by mlepyro** [comment]
CTRL+A +CTRL+C copies entire cue grid.
