### ISSUE TITLE
Add New Firework Type - All fields are required.

### ISSUE THREAD

**Issue by IllusionFireworks** [firebywire/User-Issues#32]
Annoyingly all fields need to be filled or an 'unknown error' dialogue box appears. Mostly relating to filling the 'product code' field (I never fill this). Also a product code cannot be repeated so I cannot simply just use '0' every time as this also generates 'unknown error'.

**Comment by mlepyro** [comment]
This is because you need a key to associate a firework.
Product code is the only logical way of doing this as it shouldn't be duplicated due to CE/ HSE etc reasons.

**Comment by IllusionFireworks** [comment]
I’m not convinced - how about things like ‘generic 75mm peony’ things are going to get messy if I keep having to fudge product codes.

Plus we have stock that I do not have codes for.
