### ISSUE TITLE
Add new song and change order - designer freezes

### ISSUE THREAD

**Issue by IllusionFireworks** [firebywire/User-Issues#33]
I have been working on a show, finale track confirmed but preceding tracks not confirmed so started work on the finale (quite a lot of work), added new preceeding tracks to the show - designer automatically places new tracks after existing tracks, when attempting to move finale track down the list designer freezes and has to be closed down using task manager.

Repeated and tried moving new track up to top of the list but same issue.

Now stuck with a show that needs to be finished but songs are in wring order (I am carrying on designing in wrong order hoping tracks can just be re-jigged).

**Comment by IllusionFireworks** [comment]
Getting a little worried about this as show is Friday.

**Comment by mlepyro** [comment]
And Check 
 - Add new song and change order -designer freezes
 After change order, Do you click "All Segments"?
 I don't know well what you mean. But in my view, you clicked any segment in segment bar
 If My thought is wrong, please detail more,
