### ISSUE TITLE
Function time not showing on Gantt feature

### ISSUE THREAD

**Issue by Optimumfireworks** [firebywire/User-Issues#37]
In v 2.0.1 the gantt feature has stopped displaying the function time before the cue in the wav display. only the duration is now shown.

personally i like the way it now looks but it is still a bug, it would be better to have a toggle to which is shown i think as then you can choose to see just the durations which was the origional suggestion anyway?

**Comment by mlepyro** [comment]
Works fine for me, need more detail please.  Screenshot?

**Comment by Optimumfireworks** [comment]
Appears to be ok now in V2.0.3. The prefire time now shows again in a thin line and the duration in the shaded block.

I would add that while it's logical that the cue line shows in the same colour as the gantt colour when in that mode rather than black, it does make them very hard to see as particularly blue blends with the wav background.

The fact that the gantt colour is shaded and allows transparency of the wav file behind also makes it very hard to see. Blocking out the background of the gantt area thats currently shaded with a white block then putting the shading on top of it, would appear no different but be much easier to see.
